services:
  mysql:
    image: mysql:8.0
    container_name: mysql-${PROJECT_NAME}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3390:3306"
    networks:
      - laravel_network
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    container_name: php-${PROJECT_NAME}
    restart: always
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - TIMEZONE=${PHP_FPM_TIMEZONE}
        - INSTALL_GD=${PHP_FPM_INSTALL_GD}
        - INSTALL_COMPRESSION=${PHP_FPM_INSTALL_COMPRESSION}
        - INSTALL_FTP=${PHP_FPM_INSTALL_FTP}
        - INSTALL_MBSTRING=${PHP_FPM_INSTALL_MBSTRING}
        - INSTALL_PDO_MYSQL=${PHP_FPM_INSTALL_PDO_MYSQL}
        - INSTALL_PDO_POSTGRESQL=${PHP_FPM_INSTALL_PDO_POSTGRESQL}
        - INSTALL_MYSQLI=${PHP_FPM_INSTALL_MYSQLI}
        - INSTALL_BCMATH=${PHP_FPM_INSTALL_BCMATH}
        - INSTALL_OPCACHE=${PHP_FPM_INSTALL_OPCACHE}
        - INSTALL_APCU=${PHP_FPM_INSTALL_APCU}
        - INSTALL_INTL=${PHP_FPM_INSTALL_INTL}
        - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
        - INSTALL_TOKENIZER=${PHP_FPM_INSTALL_TOKENIZER}
        - INSTALL_JSON_XML=${PHP_FPM_INSTALL_JSON_XML}
        - INSTALL_CURL=${PHP_FPM_INSTALL_CURL}
        - INSTALL_OPENSSL=${PHP_FPM_INSTALL_OPENSSL}
        - INSTALL_COMPOSER=${PHP_FPM_INSTALL_COMPOSER}
        - INSTALL_AMQP=${PHP_FPM_INSTALL_AMQP}
        - INSTALL_REDIS=${PHP_FPM_INSTALL_REDIS}
        - INSTALL_KAFKA=${PHP_FPM_INSTALL_KAFKA}
    volumes:
      - .:/var/www/html
    networks:
      - laravel_network
    depends_on:
      - mysql

  nginx:
    container_name: nginx-${PROJECT_NAME}
    restart: always
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel_network
    depends_on:
      - php

networks:
  laravel_network:
    driver: bridge

volumes:
  mysql_data:
